<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "j17_prorrogacoes".
 * Part of this class was self-generated by the Framework 
 *  
 * @author Pedro Frota <pvmf@icomp.ufam.edu.br>
 *
 * @property integer $id
 * @property integer $idAluno
 * @property string $dataSolicitacao
 * @property integer $qtdDias
 * @property string $justificativa
 * @property string $previa
 * @property integer $status
 * 
 * Obtained through relationships:
 * 
 * @property Aluno $aluno
 * @property User $orientador0
 * 
 * Symbolic, responsible for business rules and search:
 * 
 * @property string orientador
 * @property string matricula
 * @property string linhaPesquisa
 * @property string dataSolicitacao0
 * @property string dataInicio0
 * 
 */
class Prorrogacao extends \yii\db\ActiveRecord
{
    public $orientador;
    public $matricula;
    public $linhaPesquisa;
    public $dataSolicitacao0;
    public $dataInicio0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'j17_prorrogacoes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'idAluno', 'dataSolicitacao', 'qtdDias', 'justificativa', 'previa', 'status'], 'required'],
            [['id', 'idAluno', 'qtdDias', 'status'], 'integer'],
            [['matricula', 'orientador', 'dataSolicitacao', 'dataInicio', 'dataInicio0', 'dataSolicitacao0'], 'safe'],
            [['dataInicio0', 'dataSolicitacao0'], 'date', 'format' => 'php:d/m/Y'],
            [['justificativa', 'previa'], 'string'],
            [['idAluno'], 'exist', 'skipOnError' => true, 'targetClass' => Aluno::className(), 'targetAttribute' => ['idAluno' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID do Trancamento',
            'idAluno' => 'Aluno',
            'matricula' => 'Matrícula',
            'linhaPesquisa' => 'Linha de Pesquisa',
            'dataSolicitacao' => 'Data Solicitação',
            'qtdDias' => 'Qtd. Dias',
            'dataInicio' => 'Início',
            'dataInicio0' => 'Início',
            'orientador' => 'Orientador',
            'justificativa' => 'Justificativa',
            'previa' => 'Previa',
            'status' => 'Status',
        ];
    }

    /**
     * Gets the student object
     * 
     * @author Pedro Frota <pvmf@icomp.ufam.edu.br>
     * 
     * @return \yii\db\ActiveQuery
     */
    public function getAluno()
    {
        return $this->hasOne(Aluno::className(), ['id' => 'idAluno']);
    }

    /**
     * Gets the advisor object
     * 
     * @author Pedro Frota <pvmf@icomp.ufam.edu.br>
     * 
     * @return \yii\db\ActiveQuery
     */

    public function getOrientador0() {
        return $this->hasOne(User::className(), ['id' => 'orientador'])->via('aluno');
    }
}
