<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "j17_trancamentos".
 * Most of the methods contained in this class were self-generated by the Framework
 * 
 * @author Pedro Frota <pvmf@icomp.ufam.edu.br>
 *
 * @property integer $id
 * @property integer $idAluno
 * @property string $dataSolicitacao
 * @property string $dataAprovOrientador
 * @property string $dataInicio
 * @property string $prevTermino
 * @property string $dataTermino
 * @property string $justificativa
 * @property string $documento
 * @property integer $status
 *
 * @property Aluno $aluno
 */
class Trancamento extends \yii\db\ActiveRecord
{
    public $documento0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'j17_trancamentos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['idAluno', 'dataSolicitacao', 'dataInicio', 'prevTermino', /*'dataTermino',*/ 'justificativa', 'documento' /*, 'status'*/], 'required'],
            [['idAluno', 'status', 'qtdDias'], 'integer'],
            [['dataSolicitacao', 'orientador', 'dataAprovOrientador', 'dataInicio', 'dataTermino'], 'safe'],
            [['documento'], 'string'],
            [['documento0'], 'file', 'extensions' => 'pdf'],
            [['justificativa'], 'string', 'max' => 250],
            [['idAluno'], 'exist', 'skipOnError' => true, 'targetClass' => Aluno::className(), 'targetAttribute' => ['idAluno' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idAluno' => 'Nome',
            'dataSolicitacao' => 'Data Solicitação',
            'dataInicio' => 'Início',
            'orientador' => 'Orientador',
            'qtdDias' => 'Quantidade de dias',
            'dataTermino' => 'Data Término',
            'justificativa' => 'Justificativa',
            'documento' => 'Documento',
            'status' => 'Status',
        ];
    }

    /**
     * Gets the student ID
     * 
     * @author Pedro Frota <pvmf@icomp.ufam.edu.br>
     */
    public function getAluno()
    {
        return $this->hasOne(Aluno::className(), ['id' => 'idAluno']);
    }

    /**
     * Gets the student advisor ID
     * 
     * @author Pedro Frota <pvmf@icomp.ufam.edu.br>
     */
    public function getOrientador() {
        return $this->hasOne(Aluno::className(), ['id' => 'idAluno']);
    }
}
